-- ═══════════════════════════════════════════════════════════════
-- TUATH COIR - SEED DATA
-- Initial product catalog with exact pricing
-- ═══════════════════════════════════════════════════════════════

INSERT INTO products (sku, name, description, category, price, cost_price, supplier, supplier_product_id, images) VALUES

-- ═══════════════════════════════════════════════════════════════
-- IRISH APPAREL (Print-on-Demand via Printful)
-- ═══════════════════════════════════════════════════════════════

('TC-TSHIRT-001',
 'Celtic Clover T-Shirt',
 'Premium Bella+Canvas unisex tee featuring our signature hand-designed Celtic clover. Soft 100% combed cotton, modern fit. Available in Forest Green, Black, White, and Heather Gray. Sizes S-2XL. Printed on-demand with eco-friendly inks. Perfect for those who wear their Irish heritage with pride.',
 'Irish Apparel',
 29.99,
 12.95,
 'Printful',
 'PRINTFUL_TSHIRT_CLOVER',
 '["https://via.placeholder.com/500/006400/FFFFFF?text=Celtic+Clover+Tee"]'),

('TC-HOODIE-001',
 'Celtic Knot Hoodie',
 'Cozy heavyweight hoodie featuring intricate Celtic knot artwork. Perfect for cool Irish evenings or representing your heritage year-round. Soft fleece interior, adjustable drawstrings, kangaroo pocket. Unisex sizing in Forest Green and Black. Premium quality construction built to last.',
 'Irish Apparel',
 49.99,
 28.50,
 'Printful',
 'PRINTFUL_HOODIE_KNOT',
 '["https://via.placeholder.com/500/006400/FFFFFF?text=Celtic+Hoodie"]'),

('TC-HAT-001',
 'Shamrock Embroidered Hat',
 'Classic snapback cap with premium embroidered shamrock and TC monogram. Structured 6-panel design, adjustable plastic snap closure. One size fits most. Durable construction perfect for everyday wear. Show your Irish pride in style wherever you go.',
 'Irish Apparel',
 24.99,
 11.50,
 'Printful',
 'PRINTFUL_HAT_SHAMROCK',
 '["https://via.placeholder.com/500/006400/FFFFFF?text=Shamrock+Hat"]'),

('TC-TANK-001',
 'Celtic Knot Tank Top',
 'Lightweight jersey tank with bold Celtic knot design. Perfect for gym, summer wear, or layering. Bella+Canvas quality construction. Available in Green, Black, White. Sizes S-2XL. Breathable fabric keeps you comfortable during any activity.',
 'Irish Apparel',
 26.99,
 13.25,
 'Printful',
 'PRINTFUL_TANK_KNOT',
 '["https://via.placeholder.com/500/006400/FFFFFF?text=Celtic+Tank"]'),

('TC-LONGSLEEVE-001',
 'Tuath Coir Long Sleeve Tee',
 'Year-round staple with signature Tuath Coir branding and Celtic-inspired design. Comfortable long sleeves, quality Bella+Canvas construction. Forest Green and Black available. Premium fabric that gets softer with every wash. Built for comfort and durability.',
 'Irish Apparel',
 34.99,
 16.50,
 'Printful',
 'PRINTFUL_LONGSLEEVE',
 '["https://via.placeholder.com/500/006400/FFFFFF?text=Long+Sleeve"]'),

-- ═══════════════════════════════════════════════════════════════
-- MENS HYGIENE (Dropshipping via EPROLO, Zendrop, CJdropshipping)
-- ═══════════════════════════════════════════════════════════════

('TC-BEARD-001',
 'Premium Beard Grooming Kit',
 'Complete 5-piece professional beard care set perfect for the modern Irish gentleman. Includes: premium beard oil (1oz, cedarwood scent), styling balm (2oz), natural boar bristle brush, dual-sided wooden comb, and precision trimming scissors. All in handsome gift-ready box. Everything needed for a well-groomed, distinguished beard.',
 'Mens Hygiene',
 39.99,
 15.50,
 'EPROLO',
 'EPROLO_BEARD_KIT_001',
 '["https://via.placeholder.com/500/8B4513/FFFFFF?text=Beard+Kit"]'),

('TC-SKIN-001',
 'Daily Skincare Set for Men',
 'Complete 4-step daily routine designed specifically for men who care about their skin. Includes gentle foaming cleanser (4oz), balancing toner mist (3oz), lightweight oil-free moisturizer (2oz), and revitalizing eye cream (0.5oz). Natural ingredients, fresh masculine scent. Perfect for skincare beginners or enthusiasts. Visible results in 2 weeks.',
 'Mens Hygiene',
 34.99,
 12.00,
 'Zendrop',
 'ZENDROP_SKINCARE_001',
 '["https://via.placeholder.com/500/4682B4/FFFFFF?text=Skincare+Set"]'),

('TC-TRAVEL-001',
 'Travel Hygiene Essentials Kit',
 'TSA-approved travel set for the man on the go. Includes: shampoo (3oz), body wash (3oz), deodorant stick (travel size), toothbrush with collapsible case, and toothpaste (1oz). All in leak-proof containers within a compact premium leather toiletry bag. Perfect for business trips, weekends away, or gym bag. Never be unprepared again.',
 'Mens Hygiene',
 29.99,
 10.75,
 'EPROLO',
 'EPROLO_TRAVEL_001',
 '["https://via.placeholder.com/500/696969/FFFFFF?text=Travel+Kit"]'),

('TC-COLOGNE-001',
 'Irish Woods Cologne + Deodorant Set',
 'Masculine woodland fragrance inspired by the forests of Ireland. Rich notes of cedarwood, Irish pine, and subtle moss undertones. Set includes 100ml cologne spray and matching aluminum-free deodorant stick. Long-lasting natural scent that evolves throughout the day. Your signature fragrance awaits.',
 'Mens Hygiene',
 44.99,
 18.20,
 'CJdropshipping',
 'CJ_COLOGNE_WOODS_001',
 '["https://via.placeholder.com/500/654321/FFFFFF?text=Cologne+Set"]'),

('TC-SHAVE-001',
 'Classic Wet Shaving Kit',
 'Traditional wet shaving set for the gentleman who appreciates timeless grooming rituals. Includes: premium safety razor with 10 replacement blades, genuine badger hair shaving brush, rich sandalwood shaving cream (5oz), and soothing aftershave balm (4oz). Experience the art of a proper shave. Your face will thank you.',
 'Mens Hygiene',
 49.99,
 22.50,
 'Zendrop',
 'ZENDROP_SHAVE_001',
 '["https://via.placeholder.com/500/8B7355/FFFFFF?text=Shaving+Kit"]'),

('TC-HAIR-001',
 'Hair Styling Product Set',
 '3-piece professional styling set for any look. Includes: matte clay (2oz, strong hold with natural finish), classic pomade (2oz, medium hold with shine), and texturizing sea salt spray (4oz). Works with all hair types and lengths. Create anything from casual tousled to slicked-back formal. Lightweight formulas, no residue.',
 'Mens Hygiene',
 32.99,
 13.80,
 'EPROLO',
 'EPROLO_HAIR_001',
 '["https://via.placeholder.com/500/2F4F4F/FFFFFF?text=Hair+Products"]'),

-- ═══════════════════════════════════════════════════════════════
-- HANDMADE BATH (Artisan via Faire, Wholesale Botanics)
-- ═══════════════════════════════════════════════════════════════

('TC-SOAP-MOSS-001',
 'Irish Moss Moisturizing Soap',
 'Handcrafted artisan soap made with real Irish moss extract harvested from the Celtic coast. Each bar is hand-poured and cured for 6 weeks for optimal quality and longevity. Ocean-fresh scent transports you to the cliffs of Ireland. Deeply moisturizing, perfect for dry skin. Approximately 4oz bar. Natural ingredients only.',
 'Handmade Bath',
 9.99,
 3.50,
 'Faire',
 'FAIRE_SOAP_MOSS_001',
 '["https://via.placeholder.com/500/87CEEB/FFFFFF?text=Irish+Moss+Soap"]'),

('TC-SOAP-SALT-001',
 'Celtic Sea Salt Exfoliating Bar',
 'Gentle exfoliating soap with authentic Celtic sea salt crystals and therapeutic essential oils. Masculine cedar and mint scent. Perfect for rough hands, full body scrub, or pre-shave prep. Handmade in small batches by Irish artisans. Natural ingredients buff away dead skin revealing smoother complexion. 4oz bar.',
 'Handmade Bath',
 11.99,
 4.00,
 'Faire',
 'FAIRE_SOAP_SALT_001',
 '["https://via.placeholder.com/500/B0C4DE/FFFFFF?text=Sea+Salt+Soap"]'),

('TC-SOAP-CLOVER-001',
 'Shamrock Clover Gentle Soap',
 'Adorable shamrock-shaped soap infused with real clover extract from Irish meadows. Mild formula perfect for sensitive skin or daily face washing. Light herbal scent reminiscent of spring in Ireland. Makes an excellent gift. Hand-molded and beautifully wrapped. Gentle enough for all skin types. 3.5oz bar.',
 'Handmade Bath',
 9.99,
 3.50,
 'PrivateLabel',
 'PL_SOAP_CLOVER_001',
 '["https://via.placeholder.com/500/90EE90/FFFFFF?text=Shamrock+Soap"]'),

('TC-SOAP-PEAT-001',
 'Irish Peat Detox Bar',
 'Unique detox soap made with activated charcoal and genuine Irish peat moss. Draws out impurities and toxins from skin while moisturizing. Deep cleansing without stripping natural oils. Earthy, grounding scent connects you to ancient Ireland. A true piece of Irish heritage in your shower. 4oz handmade bar.',
 'Handmade Bath',
 12.99,
 4.50,
 'Faire',
 'FAIRE_SOAP_PEAT_001',
 '["https://via.placeholder.com/500/2F4F4F/FFFFFF?text=Peat+Soap"]'),

('TC-SOAP-BEER-001',
 'Guinness Stout Beer Soap',
 'Yes, made with REAL Guinness! The famous Irish stout creates an incredibly rich, creamy lather while moisturizing your skin. Subtle malty scent that mellows beautifully as the soap cures. Perfect conversation starter and unique gift for beer lovers. Handcrafted in small batches. 4oz bar. Sláinte!',
 'Handmade Bath',
 13.99,
 5.00,
 'Faire',
 'FAIRE_SOAP_BEER_001',
 '["https://via.placeholder.com/500/1C1C1C/FFFFFF?text=Guinness+Soap"]'),

('TC-BATH-001',
 'Celtic Sea Minerals Bath Soak',
 '16oz jar of pure Celtic sea salt minerals combined with therapeutic essential oils. Eucalyptus and mint invigorate while mineral-rich salts soothe tired muscles and joints. 8-10 luxurious baths per jar. Perfect after a long day or intense workout. Cork-sealed glass jar keeps minerals fresh. Transform your bath into an Irish spa.',
 'Handmade Bath',
 19.99,
 7.50,
 'WholesaleBotanics',
 'WB_BATH_SOAK_001',
 '["https://via.placeholder.com/500/4682B4/FFFFFF?text=Bath+Soak"]'),

('TC-SCRUB-001',
 'Irish Spring Body Scrub',
 'Energizing sugar scrub made with genuine Irish spring water and fresh mint extract. Exfoliates dead skin cells revealing smoother, healthier complexion. Not too rough, not too gentle - perfectly balanced. Fresh, invigorating scent wakes you up. 8oz jar. Paraben-free, natural ingredients. Use 2-3 times weekly.',
 'Handmade Bath',
 16.99,
 6.00,
 'WholesaleBotanics',
 'WB_SCRUB_001',
 '["https://via.placeholder.com/500/98FB98/FFFFFF?text=Body+Scrub"]'),

('TC-BUTTER-001',
 'Clover Honey Body Butter',
 'Whipped shea butter enriched with pure Irish clover honey. Ultra-moisturizing without feeling greasy or heavy. Sweet, natural honey scent. Perfect for dry skin, rough elbows and knees, cracked heels. A little goes a long way. 4oz jar. Handmade in small batches. Skin feels soft and supple all day.',
 'Handmade Bath',
 18.99,
 7.00,
 'Faire',
 'FAIRE_BUTTER_001',
 '["https://via.placeholder.com/500/FFD700/000000?text=Body+Butter"]'),

('TC-BEARD-OIL-001',
 'Irish Whiskey Beard Oil',
 'Premium beard conditioning oil with sophisticated Irish whiskey barrel wood scent. Expertly blended jojoba, argan, and sweet almond oils. Softens coarse beard hair, conditions skin underneath, eliminates itch and flaking. Just 3-5 drops daily. Dropper bottle ensures no waste. 1oz. A true gentleman''s essential grooming product.',
 'Handmade Bath',
 16.99,
 5.50,
 'WholesaleBotanics',
 'WB_BEARD_OIL_001',
 '["https://via.placeholder.com/500/8B4513/FFFFFF?text=Beard+Oil"]'),

('TC-COLOGNE-OIL-001',
 'Celtic Woods Cologne Roll-On Oil',
 'Concentrated cologne oil in convenient roll-on applicator. Complex scent profile: cedarwood base, Irish pine heart notes, moss and subtle whiskey undertones. Long-lasting (8+ hours), alcohol-free so it won''t dry your skin. 10ml glass roller bottle. Masculine and refined. Perfect for daily wear or special occasions.',
 'Handmade Bath',
 14.99,
 4.50,
 'PrivateLabel',
 'PL_COLOGNE_ROLL_001',
 '["https://via.placeholder.com/500/654321/FFFFFF?text=Cologne+Oil"]'),

-- ═══════════════════════════════════════════════════════════════
-- BUNDLES (Multi-supplier combinations)
-- ═══════════════════════════════════════════════════════════════

('TC-BUNDLE-GENT-001',
 'The Irish Gentleman Bundle',
 'Everything the modern Irishman needs in one package. Includes our bestselling Celtic Clover T-Shirt (your choice of color and size) plus our Premium Beard Grooming Kit (5 pieces). Perfect starter pack for yourself or as a gift. Represent your heritage while maintaining a well-groomed appearance. Save $5 when bought together vs. individual purchase.',
 'Bundles',
 64.99,
 28.45,
 'Multiple',
 'BUNDLE_GENTLEMAN_001',
 '["https://via.placeholder.com/500/006400/FFD700?text=Gentleman+Bundle"]'),

('TC-BUNDLE-GROOM-001',
 'Complete Grooming Collection',
 'Total transformation package for the man who wants it all. Includes: Men''s Daily Skincare Set (4 products), Classic Wet Shaving Kit (4 pieces), and Hair Styling Product Set (3 products). Everything needed for face, beard, and hair care. Professional results at home. Save $15 vs. buying separately. Invest in yourself.',
 'Bundles',
 89.99,
 49.55,
 'Multiple',
 'BUNDLE_GROOMING_001',
 '["https://via.placeholder.com/500/8B4513/FFFFFF?text=Grooming+Bundle"]'),

('TC-BUNDLE-BATH-001',
 'Irish Bath Ritual Bundle',
 'Luxury bath experience inspired by Irish spas and ancient Celtic bathing traditions. Includes: 2 handmade soaps of your choice, Celtic Sea Minerals Bath Soak (16oz), and Clover Honey Body Butter (4oz). Complete self-care ritual for relaxation and rejuvenation. Beautiful gift packaging available. Save $10 vs. individual items.',
 'Bundles',
 44.99,
 18.00,
 'Multiple',
 'BUNDLE_BATH_001',
 '["https://via.placeholder.com/500/4682B4/FFFFFF?text=Bath+Bundle"]'),

('TC-BUNDLE-STARTER-001',
 'Tuath Coir Starter Pack',
 'Best introduction to the Tuath Coir brand and lifestyle. Includes: Celtic Clover T-Shirt (size and color choice), Shamrock Embroidered Hat, and Travel Hygiene Kit. Represent your Irish heritage in style while staying fresh on the go. Our most popular gift bundle. Save $10. Everything you need to start your journey with us.',
 'Bundles',
 79.99,
 35.20,
 'Multiple',
 'BUNDLE_STARTER_001',
 '["https://via.placeholder.com/500/006400/FFFFFF?text=Starter+Pack"]'),

('TC-BUNDLE-ULTIMATE-001',
 'Ultimate Celtic Care Collection',
 'Our most comprehensive package for the discerning Irish gentleman. Includes: Celtic Knot Hoodie (size choice), Complete Grooming Collection (11 products), 3 Handmade Soaps (your choice), Irish Whiskey Beard Oil, and Celtic Woods Cologne. Everything a proud Irishman needs. Premium gift box included. Save $30. The ultimate self-care investment.',
 'Bundles',
 129.99,
 68.00,
 'Multiple',
 'BUNDLE_ULTIMATE_001',
 '["https://via.placeholder.com/500/006400/FFD700?text=Ultimate+Collection"]');
